version: '3'

services:

  nsck:
    build: .
    restart: always
    volumes:
      - ./conf:/usr/local/openresty/nginx/conf:ro
      - ./scripts:/scripts:ro
      - /proc:/host/proc:ro
    ports:
      - 127.0.0.1:9559:9559